### ISSUE TITLE
Cat老师您好，DevToolsCore.framework没有找到创建新工程的方法

### ISSUE THREAD

**Issue by cheng-ren** [Cat1237/turbo-journey#1]
DevToolsCore.framework可以创建新工程吗？
有一个任务需要CI创建工程，不想依赖外部环境ruby，想使用DevToolsCore，可以实现吗？

**Comment by Cat1237** [comment]
> DevToolsCore.framework可以创建新工程吗？ 有一个任务需要CI创建工程，不想依赖外部环境ruby，想使用DevToolsCore，可以实现吗？

肯定是能的，但是这样的话，得仔细探索不少东西。你可以创建一个空的作为默认模版，然后用哪些会的API，往里面添加。或者不想用ruby的话，py也有相关的功能

**Comment by cheng-ren** [comment]
感谢老师回复。
